# Production overrides for N8N Automation Platform
# Use with: docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d

services:
  n8n:
    environment:
      - N8N_LOG_LEVEL=warn
      - N8N_LOG_OUTPUT=file
      - N8N_LOG_FILE_LOCATION=/home/node/.n8n/logs/
      - N8N_ONBOARDING_FLOW_DISABLED=true
      - N8N_SECURE_COOKIE=true
      - N8N_EXECUTIONS_DATA_SAVE_ON_SUCCESS=first
      - N8N_EXECUTIONS_DATA_MAX_AGE=168  # 7 days in production
      - N8N_EXECUTIONS_DATA_PRUNE_MAX_COUNT=10000
      - N8N_WORKFLOWS_DEFAULT_NAME=Client Workflow
      - N8N_DISABLE_PRODUCTION_MAIN_PROCESS=false
      - N8N_SKIP_WEBHOOK_DEREGISTRATION_SHUTDOWN=false
      # Production authentication and runners configuration
      - N8N_RUNNERS_ENABLED=true
      - N8N_OWNER_EMAIL=${N8N_OWNER_EMAIL:-admin@your-domain.com}
      - N8N_PROTOCOL=https
      - N8N_HOST=${N8N_HOST:-your-domain.com}
      - WEBHOOK_URL=${WEBHOOK_URL:-https://your-domain.com}
    healthcheck:
      retries: 5
      start_period: 90s
      timeout: 30s
      interval: 45s
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'

  postgres:
    healthcheck:
      retries: 5
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.3'
        reservations:
          memory: 128M
          cpus: '0.1'

  redis:
    command: >
      redis-server
      --requirepass ${REDIS_PASSWORD}
      --maxmemory 128mb
      --maxmemory-policy allkeys-lru
      --save 60 1000
      --appendonly yes
      --appendfsync everysec
    healthcheck:
      retries: 5
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.2'
        reservations:
          memory: 64M
          cpus: '0.1'